# fly.toml app configuration file generated for mindora on 2023-12-22T18:27:28+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mindora"
primary_region = "sin"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[env]
  RAILS_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
