# fly.toml app configuration file generated for mindora-green-mountain on 2023-12-22T18:46:54+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mindora"
primary_region = "sin"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
app = "./bin/rails server"
#worker = "bundle exec good_job start"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[env]
RAILS_ENV = "production"
TENCENT_CLOUD_COS_ENDPOINT = "https://cos.ap-singapore.myqcloud.com"
TENCENT_CLOUD_COS_BUCKET = "chanpinwangwangprod-1256601241"
RAILS_LOG_TO_STDOUT = "true"
AZURE_OPENAI_URI = "https://pmwangwang-au.openai.azure.com/openai/deployments/gpt-4"