name: Fly Deploy
on:
  push:
    branches:
      - main
      - test
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Test
        if: github.ref == 'refs/heads/test'
        run: flyctl deploy -c fly.test.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TEST_ENV_TOKEN }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: flyctl deploy -c fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_PRODUCTION_ENV_TOKEN }}
          TENCENT_CLOUD_COS_ENDPOINT: "https://cos.ap-singapore.myqcloud.com"
